config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/captain_america'

  get 'static_pages/thor'

  get 'static_pages/hulk'

  get 'static_pages/ant_man'

  get 'static_pages/black_panther'

  get 'static_pages/spider_man'

  get 'static_pages/iron_man'

  resources :sessions, only:[:new, :create, :destroy, :add]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root to: 'static_pages#home'
  match '/spotlight', to: 'static_pages#spotlight', via: 'get'
  match '/iron_man', to: 'static_pages#iron_man', via: 'get'
  match '/captain_america', to: 'static_pages#captain_america', via: 'get'
  match '/thor', to: 'static_pages#thor', via: 'get'
  match '/hulk', to: 'static_pages#hulk', via: 'get'
  match '/ant_man', to: 'static_pages#ant_man', via: 'get'
  match '/black_panther', to: 'static_pages#black_panther', via: 'get'
  match '/spider_man', to: 'static_pages#spider_man', via: 'get'

  resources :users
  resources :comics

  get '/comics/:id/add', to: 'comics#add', as: 'currentcomic'

  get '/comics/:id/read', to: 'comics#read', as: 'currentcomicread'

  get '/comics/:id', to: 'static_pages#find', as: 'findironman'

  get '/comics/:id', to: 'static_pages#find', as: 'findcaptainamerica'

  get '/comics/:id', to: 'static_pages#find', as: 'findthor'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    redirect_to user_path(@current_user) if signed_in?
  end

  def spotlight
  end

  def iron_man
    @comic = Comic.find(1)
    @comic2 = Comic.find(2)
    @comic3 = Comic.find(3)
    @comic4 = Comic.find(4)
    @comic5 = Comic.find(5)
    @comic6 = Comic.find(6)
    @comic7 = Comic.find(7)
  end

  def captain_america
    @comic8 = Comic.find(8)
    @comic9 = Comic.find(9)
    @comic10 = Comic.find(10)
    @comic11 = Comic.find(11)
    @comic12 = Comic.find(12)
    @comic13 = Comic.find(13)
    @comic14 = Comic.find(14)
  end

  def thor
    @comic15 = Comic.find(15)
    @comic16 = Comic.find(16)
    @comic17 = Comic.find(17)
    @comic18 = Comic.find(18)
    @comic19 = Comic.find(19)
    @comic20 = Comic.find(20)
    @comic21 = Comic.find(21)
  end

  def hulk
    @comic22 = Comic.find(22)
    @comic23 = Comic.find(23)
    @comic24 = Comic.find(24)
    @comic25 = Comic.find(25)
    @comic26 = Comic.find(26)
    @comic27 = Comic.find(27)
  end

  def ant_man
    @comic28 = Comic.find(28)
    @comic29 = Comic.find(29)
    @comic30 = Comic.find(30)
    @comic31 = Comic.find(31)
    @comic32 = Comic.find(32)
    @comic33 = Comic.find(33)
    @comic34 = Comic.find(34)
  end

  def black_panther
    @comic35 = Comic.find(35)
    @comic36 = Comic.find(36)
    @comic37 = Comic.find(37)
    @comic38 = Comic.find(38)
    @comic39 = Comic.find(39)
    @comic40 = Comic.find(40)
    @comic41 = Comic.find(41)
    @comic42 = Comic.find(42)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/ant_man.html.erb
<body class="ant-img">
<div class="page-header">
  <h1>Ant Man</h1>
<h3>If you want a quick 101 on Ant Man look no further:</h3>
  <h5>Dr. Henry "Hank" Pym, is an American biochemist with extensive knowledge in various scientific fields. Pym discovered a rare group of subatomic particles, which have become known as the "Pym Particles." Pym was able, through the application of magnetic fields, to entrap the particles within two separate serums. One serum would reduce the size of persons and objects, and the other would restore them to their normal size. He used these serums and took on the name Ant Man.</h5>
</div>


<p>Current Series:</p>
<%= link_to 'Ant-Man', findcaptainamerica_path(@comic28) %> <br>
<%= link_to 'Avengers Origins: Ant-Man & the Wasp', findcaptainamerica_path(@comic29) %> <br>

<br><p>Essentials:</p>

<%= link_to 'Tales to Astonish', findcaptainamerica_path(@comic30) %> <br>
<%= link_to 'Avengers', findcaptainamerica_path(@comic31) %> <br>
<%= link_to 'Avengers', findcaptainamerica_path(@comic32) %> <br>
<%= link_to 'Ant-Man', findcaptainamerica_path(@comic33) %> <br>
<%= link_to 'Irredeemable Ant-Man', findcaptainamerica_path(@comic34) %> <br>


<br><p>Supplementary:</p>

</body>

app/views/static_pages/black_panther.html.erb
<body class="panther-img">
<div class="page-header">
  <h1>Black Panther</h1>
<h3>If you want a quick 101 on Black Panther look no further:</h3>
  <h5>The Black Panther is the ceremonial title given to the chief of the Panther Tribe of the advanced African nation of Wakanda. In addition to ruling the country, he is also chief of its various tribes (collectively referred to as the Wakandas). The Panther habit is a symbol of office (head of state) and is used even during diplomatic missions. The Panther is a hereditary title, but one still must earn it.</h5>
</div>

<a href="https://youtu.be/-6vWD5TLtEs">Black Panther 101 Video</a>


<p>Current Series:</p>
<%= link_to 'Black Panther', findcaptainamerica_path(@comic35) %> <br>

<br><p>Essentials:</p>

<%= link_to 'Fantastic Four', findcaptainamerica_path(@comic36) %> <br>
<%= link_to 'Black Panther', findcaptainamerica_path(@comic37) %> <br>
<%= link_to 'Black Panther', findcaptainamerica_path(@comic38) %> <br>
<%= link_to 'Black Panther', findcaptainamerica_path(@comic39) %> <br>
<%= link_to 'Claws of the Panther', findcaptainamerica_path(@comic40) %> <br>
<%= link_to 'Black Panther: The Man Without Fear', findcaptainamerica_path(@comic41) %> <br>
<%= link_to 'Black Panther: The Most Dangerous Man Alive', findcaptainamerica_path(@comic42) %> <br>


<br><p>Supplementary:</p>

</body>

app/views/static_pages/captain_america.html.erb
<body class="cap-img">
<div class="page-header">
  <h1>Captain America: The First Avenger</h1>
<h3>If you want a quick 101 on Captain America look no further:</h3>
  <h5>Vowing to serve his country any way he could, young Steve Rogers took the super soldier serum to become America's one-man army. Fighting for the red, white and blue for over 60 years, Captain America is the living, breathing symbol of freedom and liberty.</h5>
</div>


<p>Current Series:</p>
<%= link_to 'Captain America', findcaptainamerica_path(@comic8) %> <br>

<br><p>Essentials:</p>

<%= link_to 'Captain America: The New Deal', findcaptainamerica_path(@comic9) %> <br>
<%= link_to 'Truth: Red, White, & Black', findcaptainamerica_path(@comic10) %> <br>
<%= link_to 'Captain America', findcaptainamerica_path(@comic11) %> <br>
<%= link_to 'Captain America: Reborn', findcaptainamerica_path(@comic12) %> <br>
<%= link_to 'Steve Roger: Super Soldier', findcaptainamerica_path(@comic13) %> <br>
<%= link_to 'Captain America: Shattered Heroes', findcaptainamerica_path(@comic14) %> <br>


<br><p>Supplementary:</p>

</body>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="text-center jumbotron">
  <h1>Welcome to Comic Catch Up</h1>
  <h3>Sign up to start adding comics to your list.</h3>
  <br/>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  <%= link_to "Sign in",      signin_path, class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/hulk.html.erb
<body class="hulk-img">
<div class="page-header">
  <h1>The Incredible Hulk</h1>
<h3>If you want a quick 101 on The Hulk look no further:</h3>
  <h5>Caught in a gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. An all too often misunderstood hero, the angrier the Hulk gets, the stronger the Hulk gets.</h5>
</div>


<p>Current Series:</p>
<%= link_to 'Indestructible Hulk', findcaptainamerica_path(@comic22) %> <br>
<%= link_to 'Hulk', findcaptainamerica_path(@comic23) %> <br>

<br><p>Essentials:</p>

<%= link_to 'Incredible Hulk', findcaptainamerica_path(@comic24) %> <br>
<%= link_to 'Incredible Hulk', findcaptainamerica_path(@comic25) %> <br>
<%= link_to 'World War Hulk', findcaptainamerica_path(@comic26) %> <br>
<%= link_to 'Hulk', findcaptainamerica_path(@comic27) %> <br>


<br><p>Supplementary:</p>

</body>

app/views/static_pages/iron_man.html.erb
<body class="iron-img">
<div class="page-header">
  <h1>The Invincible Iron Man</h1>
  <h3>If you want a quick 101 on Iron Man look no further:</h3>
  <h5>Wounded, captured and forced to build a weapon by his enemies, billionaire industrialist Tony Stark instead created an advanced suit of armor to save his life and escape captivity. Now with a new outlook on life, Tony uses his money and intelligence to make the world a safer, better place as Iron Man.</h5>
</div>


<p>Current Series:</p>
<%= link_to 'Iron Man', findironman_path(@comic) %> <br>

<br><p>Essentials:</p>

<%= link_to 'Tales of Suspense', findironman_path(@comic2) %> <br>
<%= link_to 'Avengers', findironman_path(@comic3) %> <br>
<%= link_to 'The Invincible Iron Man', findironman_path(@comic4) %> <br>
<%= link_to 'West Coast Avengers', findironman_path(@comic5) %> <br>
<%= link_to 'Iron Man', findironman_path(@comic6) %> <br>
<%= link_to 'Invincible Iron Man', findironman_path(@comic7) %> <br>


<br><p>Supplementary:</p>

</body>

app/views/static_pages/spider_man.html.erb
<body class="spider-img">
  <div class="page-header">

    <h1>StaticPages#spider_man</h1>
  </div>
  <p>Find me in app/views/static_pages/spider_man.html.erb</p>

  <a href="https://youtu.be/-6vWD5TLtEs">here</a>

  <ul>
   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
   <li>Aliquam tincidunt mauris eu risus.</li>
   <li>Vestibulum auctor dapibus neque.</li>
</ul>


</body>

app/views/static_pages/spotlight.html.erb
<body class="list-img">
<% provide(:title, 'Spotlight') %>
<h2>This month's spotlight is on <%= link_to 'Black Panther', '/black_panther' %>.</h2>
<h4>Or choose from any MCU movie below.</h4>
<ul>
  <li><%= link_to 'Iron Man', '/iron_man' %></li>
  <li><%= link_to 'Captain America', '/captain_america' %></li>
  <li><%= link_to 'Thor', '/thor' %></li>
  <li><%= link_to 'The Hulk', '/hulk' %></li>
  <li><%= link_to 'Ant Man', '/ant_man' %></li>
  <li><%= link_to 'Black Panther', '/black_panther' %></li>
  <li><%= link_to 'Spider Man', '/spider_man' %></li>
</ul>

</body>

app/views/static_pages/thor.html.erb
<body class="thor-img">
<div class="page-header">
  <h1>Thor: The God of Thunder</h1>
<h3>If you want a quick 101 on Thor look no further:</h3>
  <h5>As the Norse God of thunder and lightning, Thor wields one of the greatest weapons ever made, the enchanted hammer Mjolnir. While others have described Thor as an over-muscled, oafish imbecile, he's quite smart and compassionate. He's self-assured, and he would never, ever stop fighting for a worthwhile cause.</h5>
</div>


<p>Current Series:</p>
<%= link_to 'Thor: God of Thunder', findcaptainamerica_path(@comic15) %> <br>
<%= link_to 'Thor', findcaptainamerica_path(@comic16) %> <br>

<br><p>Essentials:</p>

<%= link_to 'Journey Into Mystery', findcaptainamerica_path(@comic17) %> <br>
<%= link_to 'Thor', findcaptainamerica_path(@comic18) %> <br>
<%= link_to 'Balder The Brave', findcaptainamerica_path(@comic19) %> <br>
<%= link_to 'The Mighty Thor', findcaptainamerica_path(@comic20) %> <br>
<%= link_to 'Thor', findcaptainamerica_path(@comic21) %> <br>


<br><p>Supplementary:</p>

</body>