config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/captain_america'

  get 'static_pages/thor'

  get 'static_pages/hulk'

  get 'static_pages/ant_man'

  get 'static_pages/black_panther'

  get 'static_pages/spider_man'

  get 'static_pages/iron_man'

  resources :sessions, only:[:new, :create, :destroy, :add]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root to: 'static_pages#home'
  match '/spotlight', to: 'static_pages#spotlight', via: 'get'
  match '/iron_man', to: 'static_pages#iron_man', via: 'get'
  match '/captain_america', to: 'static_pages#captain_america', via: 'get'
  match '/thor', to: 'static_pages#thor', via: 'get'
  match '/hulk', to: 'static_pages#hulk', via: 'get'
  match '/ant_man', to: 'static_pages#ant_man', via: 'get'
  match '/black_panther', to: 'static_pages#black_panther', via: 'get'
  match '/spider_man', to: 'static_pages#spider_man', via: 'get'

  resources :users
  resources :comics

  get '/comics/:id/add', to: 'comics#add', as: 'currentcomic'

  get '/comics/:id/read', to: 'comics#read', as: 'currentcomicread'

  get '/comics/:id', to: 'static_pages#find', as: 'findironman'

  get '/comics/:id', to: 'static_pages#find', as: 'findcaptainamerica'

  get '/comics/:id', to: 'static_pages#find', as: 'findthor'

end

app/models/comic.rb
class Comic < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :set_comic, only: [:show, :edit, :update, :destroy, :add]
  # before_action :signed_in_user

  # GET /comics
  # GET /comics.json
  def index
    @comics = Comic.all
    # @comics = Comic.all
  end

  # GET /comics/1
  # GET /comics/1.json
  def show
  end

  # GET /comics/new
  def new
    @comic = Comic.new
  end

  # GET /comics/1/edit
  def edit
  end

  # Need to make this add comic ids to the current user!!!!!!!!
  def add
    # comic_id = comic.id
    @comics = current_user.comics.push(Comic.find(params[:id]))
    # @comic = Comic.push
    # @comic.user = current_user
  end

  def read
    @comics = current_user.comics.delete(Comic.find(params[:id]))
  end

  # POST /comics
  # POST /comics.json
  def create
    @comic = Comic.new(comic_params)

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render :show, status: :created, location: @comic }
      else
        format.html { render :new }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comics/1
  # PATCH/PUT /comics/1.json
  def update
    respond_to do |format|
      if @comic.update(comic_params)
        format.html { redirect_to @comic, notice: 'Comic was successfully updated.' }
        format.json { render :show, status: :ok, location: @comic }
      else
        format.html { render :edit }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comics/1
  # DELETE /comics/1.json
  def destroy
    @comic.destroy
    respond_to do |format|
      format.html { redirect_to comics_url, notice: 'Comic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comic
      @comic = Comic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comic_params
      params.require(:comic).permit(:title, :year, :issues, :user_ids => [])
    end
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_form.html.erb
<%= form_for(@comic) do |f| %>
  <% if @comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
      <% @comic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :issues %><br>
    <%= f.text_field :issues %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comics/add.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @comic.title %>
</p>

<p> Successfully added to your reading list! </p>

app/views/comics/edit.html.erb
<h1>Editing Comic</h1>

<%= render 'form' %>

<%= link_to 'Show', @comic %> |
<%= link_to 'Back', comics_path %>

app/views/comics/index.html.erb
<body class="list-img">
<p id="notice"><%= notice %></p>

<h1>Complete Comic List</h1>


<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Issues</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comics.each do |comic| %>
      <tr>
        <td><%= comic.title %></td>
        <td><%= comic.year %></td>
        <td><%= comic.issues %></td>
        <td><%= link_to 'Show', comic %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</body>

app/views/comics/new.html.erb
<h1>New Comic</h1>

<%= render 'form' %>

<%= link_to 'Back', comics_path %>

app/views/comics/read.html.erb
<p id="notice"><%= notice %></p>

<p> Well Read! Hope you enjoyed it. </p>

app/views/comics/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "showtext">
<p>
  <strong>Title:</strong>
  <%= @comic.title %>  |
  <%= @comic.year %>  |
  <%= @comic.issues %>
</p>
</div>

<%-# link_to 'Edit', edit_comic_path(@comic) %>
<%= link_to 'Back', comics_path %> |
<%= link_to 'Add', currentcomic_path(@comic) %> |
<%= link_to 'Read', currentcomicread_path(@comic) %>